module.exports = {
  MONGO_KEY: process.env.MONGO_KEY,
  JWT_SECRET: process.env.JWT_SECRET,
  EMAIL_SECRET: process.env.EMAIL_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  SENDGRID_KEY:	process.env.SENDGRID_KEY,
  SENDGRID_NAME: process.env.SENDGRID_NAME,
  SENDGRID_PASS: process.env.SENDGRID_PASS,
  INSTAGRAM_ACCESS_TOKEN: process.env.INSTAGRAM_ACCESS_TOKEN
};